### ISSUE TITLE
Issue with EBS Raid hanging on EBS volume creation

### ISSUE THREAD

**Issue by npchris** [albertsj1/chef-ebs#21]
I've been using this cookbook for over a year now and have yet to run into any issues. This is my first attempt at a RAID array created with this cookbook. 

It seems that it's just hanging waiting for /dev/xvdc to be mounted but it's never creating the ebs volumes in AWS.

I've tested that I can create single ebs volumes without issue on the same system with the same cookbook. I've let this run for about 2 hours and it's never gotten any further.

Below is the output from an strace on the chef worker

root@box1:/home/ubuntu# strace -p 10177
Process 10177 attached - interrupt to quit
restart_syscall(<... resuming interrupted call ...>) = -1 ETIMEDOUT (Connection timed out)
futex(0x1a57618, FUTEX_WAKE_PRIVATE, 1) = 0
clock_gettime(CLOCK_MONOTONIC, {976, 573213306}) = 0
stat("/dev/xvdc", 0x7fff2333b4b0)       = -1 ENOENT (No such file or directory)
clock_gettime(CLOCK_MONOTONIC, {976, 573604612}) = 0
clock_gettime(CLOCK_MONOTONIC, {976, 573730133}) = 0
futex(0x1a575b4, FUTEX_WAIT_BITSET_PRIVATE, 25, {986, 573730133}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x1a57618, FUTEX_WAKE_PRIVATE, 1) = 0
clock_gettime(CLOCK_MONOTONIC, {986, 574298508}) = 0
stat("/dev/xvdc", 0x7fff2333b4b0)       = -1 ENOENT (No such file or directory)
clock_gettime(CLOCK_MONOTONIC, {986, 574664859}) = 0
clock_gettime(CLOCK_MONOTONIC, {986, 574789903}) = 0
futex(0x1a575b4, FUTEX_WAIT_BITSET_PRIVATE, 27, {996, 574789903}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x1a57618, FUTEX_WAKE_PRIVATE, 1) = 0
clock_gettime(CLOCK_MONOTONIC, {996, 575247390}) = 0
stat("/dev/xvdc", 0x7fff2333b4b0)       = -1 ENOENT (No such file or directory)

Any info/advice would be greatly appreciated.

Thanks.

**Comment by dwradcliffe** [comment]
Same here.
